name: notebook
channels:
  - conda-forge
dependencies:
  # Python Core & Scientific Stack
  - python=3.10
  - pandas
  - numpy
  - scipy
  - statsmodels
  - scikit-learn
  - scikit-bio
  - matplotlib
  - seaborn
  - plotly
  - openpyxl

  # Jupyter, Dashboard & Interactivity
  - voila
  - jupyterlab
  - ipywidgets
  - ipykernel

  # R Core Engine & Python-R Bridge
  - rpy2
  - r-base
  - r-matrix
