name: notebook
channels:
  - conda-forge
dependencies:
  # Python Core & Scientific Stack
  - python=3.10
  - pandas
  - numpy
  - scipy
  - statsmodels
  - scikit-learn
  - scikit-bio
  - matplotlib
  - seaborn
  - plotly
  - openpyxl

  # Jupyter & Dashboard
  - voila
  - jupyterlab
  - ipywidgets
  - ipykernel

  # R Engine & Statistical Packages (Pre-compiled binaries)
  - rpy2
  - r-base
  - r-matrix
  - r-nloptr
  - r-lme4
  - r-pbkrtest
  - r-car
  - r-afex
  - r-emmeans
