[theme]
base = "light"
primaryColor = "#0056b3"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f6f9"
textColor = "#212529"
font = "sans serif"

[client]
showSidebarNavigation = true

[layout]
wideMode = true
